const mountains=["Everest","K2","Kanchenjunga","Lhotse","Makalu"];
const rivers=["Nile","Niger","Euphrates","Kolyma","	Ganges"];
const countries=["Afghanistan","Albania","Algeria","Andorra","Bhutan"];
const cities=["Lahore","karachi","Islamabad","Kasur","Multan"];
const languages=["Spanish","Hindi","English","French","Chinese"];
console.log(mountains);
console.log(rivers);
console.log(countries);
console.log(cities);
console.log(languages);